# Generated by Django 5.0.1 on 2024-05-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_payment_method_useraccount_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='postal_code',
        ),
    ]
