# Generated by Django 5.0.1 on 2024-04-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./fruit-images/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('supply_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
