# Generated by Django 5.0.1 on 2024-05-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_order_order_ordered_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('SSLCOMMERZ', 'SSLCOMMERZ')], default='Cash on delivery', max_length=30),
        ),
    ]
